language: node_js
node_js:
  - '11'
services:
  - docker
cache:
  directories:
    - "$HOME/docker"
    - node_modules
env:
  global:
    - PROJECT_NAME=form3-s3
jobs:
  include:
    - stage: test
      name: Run Node Tests
      script:
        - echo "Testing"